config/routes.rb
Rails.application.routes.draw do
  # get "calendar/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root to: redirect("login/index")
  get "login/index", to: "login#index", as: "login"
  post "/logout", to: "sessions#logout", as: "logout"
  get "/auth/google_oauth2/callback", to: "sessions#omniauth"
  get "sessions/logout"
  get "sessions/omniauth"

  resources :admins
  get "welcome/index", to: "welcome#index", as: "welcome"
  get "welcome/download", to: "download#download", as: "download"
  post "uploads", to: "uploads#handle_upload", as: "uploads"
  # resources :uploads, only: [ :new, :create ]

  resources :calendar, only: [ :index ] do
    get :export, on: :collection
    get :download_unassigned_rjs, on: :collection
  end

  get "calendar", to: "calendar#index"

  # Route for deleting CSV
  delete "welcome/delete_csv_files", to: "welcome#delete_csv_files", as: "delete_csv_files"
  post "welcome/handle_files", to: "welcome#handle_files", as: "handle_files"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # Use a different directory in test environment to isolate real data
    upload_path = Rails.env.test? ? "#{Rails.root}/tmp/test_uploads" : "#{Rails.root}/public/uploads"

    # Check for CSV and XLSX files in the specified directory
    @csv_files = Dir.glob("#{upload_path}/*.{csv,xlsx}")
  end

  def handle_files
    case params[:action_type]
    when "Generate Schedule"
      handle_generate_schedule
    when "Delete Selected Files"
      handle_delete_selected_files
    else
      redirect_invalid_action
    end
  end

  private

  def handle_generate_schedule
    selected_files = params[:selected_files]
    if valid_file_selection?(selected_files)
      parse_selected_files(selected_files)
    else
      redirect_to welcome_path, alert: "Please select exactly one file to parse."
    end
  end

  def valid_file_selection?(selected_files)
    selected_files.present? && selected_files.size == 1
  end

  def handle_delete_selected_files
    if params[:selected_files].present?
      delete_csv_files(params[:selected_files])
      redirect_to welcome_path, notice: "Selected files have been deleted."
    else
      redirect_to welcome_path, alert: "No files selected for deletion."
    end
  end

  def redirect_invalid_action
    redirect_to welcome_path, alert: "Invalid action."
  end


  private

  def delete_csv_files(selected_files)
    upload_path = determine_upload_path

    return unless params[:selected_files].present?

    params[:selected_files].each do |file_name|
      delete_file(upload_path, file_name)
    end
  end

  private

  def determine_upload_path
    Rails.env.test? ? "#{Rails.root}/tmp/test_uploads" : "#{Rails.root}/public/uploads"
  end

  def delete_file(upload_path, file_name)
    file_path = Rails.root.join(upload_path, file_name)

    if File.exist?(file_path)
      File.delete(file_path)
    end
  end


  def parse_selected_files(selected_files)
    upload_path = Rails.env.test? ? "#{Rails.root}/tmp/test_uploads" : "#{Rails.root}/public/uploads"

    selected_files.each do |file_name|
      file_path = Rails.root.join(upload_path, file_name)
      begin
        parse_and_create_radio_jockeys(file_path)
      rescue StandardError => e
        Rails.logger.error("Error while parsing XLSX: #{e.message}")
        flash[:alert] = "An error occurred during file parsing."
        redirect_to welcome_path and return
      end
      ScheduleProcessor.process
    end
    redirect_to calendar_path
  end

  def parse_and_create_radio_jockeys(file_path)
    RadioJockey.delete_all
    ScheduleEntry.delete_all
    %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday].each do |day|
      (0..23).each do |hour|
        ScheduleEntry.create(day: day, hour: hour, show_name: nil, last_name: nil, jockey_id: nil)
      end
    end

    xlsx = Roo::Spreadsheet.open(file_path.to_s)

    process_sheet(xlsx.sheet(0), "Returning DJ", xlsx, header_mapping)
    process_sheet(xlsx.sheet(1), "New DJ", xlsx, header_mapping)
  end

  private

  def process_sheet(sheet, dj_type, xlsx, header_mapping)
    headers = xlsx.row(1)

    column_mapping = {} # Create a mapping between headers and column indices
    headers.each_with_index do |header, index|
      column_mapping[header.strip.downcase] = index
    end

    i = 1
    sheet.each_row_streaming(offset: 1, pad_cells: true) do |row| # Skip header row
      i += 1
      if row[column_mapping[header_mapping[:member_type]]].to_s == dj_type
        create_radio_jockey(row, i, xlsx, column_mapping, header_mapping)
      end
    end
  end

  def convert_to_24_hr_format(time)
    hour, ampm = time.split(" ")
    if hour == "12"
      ampm == "AM" ? "0" : "12"
    else
      ampm == "AM" ? hour : (hour.to_i + 12).to_s
    end
  end

  def format_times(times)
    times = times.split(",")
    converted_times = []
    times.each do |time|
      converted_time = convert_to_24_hr_format(time)
      converted_times << converted_time
    end
    converted_times = converted_times.join(";")
    converted_times
  end

  def create_radio_jockey(row, row_index, xlsx, column_mapping, header_mapping)
    show_name = row[column_mapping[header_mapping[:show_name]]].to_s.strip
    if show_name.empty?
      puts "Show name is missing, thus ignoring the entry"
      return
    end

    rj_data = prepare_rj_data(row, column_mapping, header_mapping)

    existing_rj = RadioJockey.find_by(show_name: show_name)
    if existing_rj
      puts "Found an existing RJ with Show Name : ", show_name
      if should_update_rj(existing_rj, row, column_mapping, header_mapping, rj_data)
        puts "Incoming RJ has higher priority, hence using the data from the same"
        existing_rj.update(rj_data)
      end
    else
      RadioJockey.create!(rj_data)
    end
  end

  private

  def prepare_rj_data(row, column_mapping, header_mapping)
    {
      timestamp: row[column_mapping[header_mapping[:timestamp]]].value.to_s || "",
      first_name: row[column_mapping[header_mapping[:first_name]]].to_s || "",
      last_name: row[column_mapping[header_mapping[:last_name]]].to_s || "",
      uin: row[column_mapping[header_mapping[:uin]]].to_s || "",
      expected_grad: "#{row[column_mapping[header_mapping[:graduating_year]]].to_s || ""}/#{row[column_mapping[header_mapping[:graduating_month]]].to_s || ""}",
      member_type: row[column_mapping[header_mapping[:member_type]]].to_s || "",
      retaining: column_mapping.key?(header_mapping[:retaining]) ? row[column_mapping[header_mapping[:retaining]]].to_s || "No" : "No",
      semesters_in_kanm: row[column_mapping[header_mapping[:semesters_in_kanm]]].to_s || "0",
      show_name: row[column_mapping[header_mapping[:show_name]]].to_s.strip,
      dj_name: row[column_mapping[header_mapping[:dj_name]]].to_s || "",
      best_day: row[column_mapping[header_mapping[:best_day]]].to_s || "",
      best_hour: convert_to_24_hr_format(row[column_mapping[header_mapping[:best_hour]]].to_s || ""),
      alt_mon: format_times(row[column_mapping[header_mapping[:alt_mon]]].to_s || ""),
      alt_tue: format_times(row[column_mapping[header_mapping[:alt_tue]]].to_s || ""),
      alt_wed: format_times(row[column_mapping[header_mapping[:alt_wed]]].to_s || ""),
      alt_thu: format_times(row[column_mapping[header_mapping[:alt_thu]]].to_s || ""),
      alt_fri: format_times(row[column_mapping[header_mapping[:alt_fri]]].to_s || ""),
      alt_sat: format_times(row[column_mapping[header_mapping[:alt_sat]]].to_s || ""),
      alt_sun: format_times(row[column_mapping[header_mapping[:alt_sun]]].to_s || ""),
      un_jan: row[column_mapping[header_mapping[:un_jan]]].to_s || "",
      un_feb: row[column_mapping[header_mapping[:un_feb]]].to_s || "",
      un_mar: row[column_mapping[header_mapping[:un_mar]]].to_s || "",
      un_apr: row[column_mapping[header_mapping[:un_apr]]].to_s || "",
      un_may: row[column_mapping[header_mapping[:un_may]]].to_s || ""
    }
  end

  def should_update_rj(existing_rj, row, column_mapping, header_mapping, rj_data)
    member_type = rj_data[:member_type]
    semesters_in_kanm = rj_data[:semesters_in_kanm]
    expected_grad = rj_data[:expected_grad]
    timestamp = rj_data[:timestamp]

    if member_type != existing_rj.member_type
      if member_type == "Returning RJ" # Returning has higher priority, else ignore
        return true
      end
    else # Same member type
      if (semesters_in_kanm > existing_rj.semesters_in_kanm) ||
         (semesters_in_kanm == existing_rj.semesters_in_kanm && expected_grad < existing_rj.expected_grad) ||
         (semesters_in_kanm == existing_rj.semesters_in_kanm && expected_grad == existing_rj.expected_grad && timestamp < existing_rj.timestamp)
        return true
      end
    end

    false
  end


  def header_mapping
    {
      timestamp: "timestamp",
      first_name: "first name",
      last_name: "last name",
      show_name: "show name",
      graduating_year: "graduating year",
      graduating_month: "graduating month",
      retaining: "retain slot",
      semesters_in_kanm: "semesters in kanm",
      member_type: "select position applying for:",
      uin: "uin",
      dj_name: "dj name",
      best_day: "best day",
      best_hour: "best hour",

      alt_mon: "alternative timeslots [monday]",
      alt_tue: "alternative timeslots [tuesday]",
      alt_wed: "alternative timeslots [wednesday]",
      alt_thu: "alternative timeslots [thursday]",
      alt_fri: "alternative timeslots [friday]",
      alt_sat: "alternative timeslots [saturday]",
      alt_sun: "alternative timeslots [sunday]",

      un_jan: "unavailable dates [january]",
      un_feb: "unavailable dates [february]",
      un_mar: "unavailable dates [march]",
      un_apr: "unavailable dates [april]",
      un_may: "unavailable dates [may]",
      un_jun: "unavailable dates [june]",

      un_jul: "unavailable dates [july]",
      un_aug: "unavailable dates [august]",
      un_sep: "unavailable dates [september]",
      un_oct: "unavailable dates [october]",
      un_nov: "unavailable dates [november]",
      un_dec: "unavailable dates [december]"
    }
  end
end

app/views/welcome/index.html.erb
<div class="px-40 flex flex-1 justify-center py-5">
  <div class="layout-content-container flex flex-col max-w-[960px] flex-1">
    <div class="@container">
      <div class="flex flex-col gap-6 px-4 py-10 @[480px]:gap-8 @[864px]:flex-row">
        <div
          class="w-full bg-center bg-no-repeat aspect-video bg-cover rounded-xl @[480px]:h-auto @[480px]:min-w-[400px] @[864px]:w-full"
          style='background-image: url("/85303017-5836-4258-b1f8-f403759e02f1.jfif");'
        ></div>
        <div class="flex flex-col gap-6 @[480px]:min-w-[400px] @[480px]:gap-8 @[864px]:justify-center">
          <div class="flex flex-col gap-2 text-left">
            <h1
              class="text-[#111418] text-4xl font-black leading-tight tracking-[-0.033em] @[480px]:text-5xl @[480px]:font-black @[480px]:leading-tight @[480px]:tracking-[-0.033em]"
            >
                Howdy!
            </h1>
            <h4 
            >
              Please upload your RJ Preferences Spreadsheet below.
            </h4>
          </div>
        </div>
      </div>
    </div>

    <div class="flex flex-col p-4">
      <div class="flex flex-col items-center gap-6 rounded-xl border-2 border-dashed border-[#dce0e5] px-6 py-14">

        <!-- Check if CSV files are present -->
        <% if @csv_files.empty? %>
          <p class="text-[#111418] text-lg font-bold leading-tight tracking-[-0.015em] max-w-[480px] text-center">
            No files are present
          </p>
        <% else %>
          <%= form_with url: handle_files_path, method: :post do %>
            <!-- Displaying CSV files -->
            <div class="w-full max-w-lg max-h-60 overflow-y-auto border border-gray-300 rounded-lg p-4">
              <ul>
                <% @csv_files.each do |file| %>
                  <li class="text-sm text-[#111418] mb-2 flex items-center">
                    <input type="checkbox" class="mr-2" value="<%= File.basename(file) %>" name="selected_files[]">
                    <%= File.basename(file) %>
                  </li>
                <% end %>
              </ul>
            </div>

            <div class="flex gap-4">
              <div class="generate-btn field flex min-w-[84px] max-w-[240px] cursor-pointer items-center justify-center overflow-hidden rounded-xl h-10 px-4 bg-green-500 text-white text-sm font-bold leading-normal tracking-[0.015em] mt-4">
                <%= submit_tag 'Generate Schedule', name: 'action_type', value: 'Generate Schedule' %>
              </div>

              <div class="delete-btn field flex min-w-[84px] max-w-[240px] cursor-pointer items-center justify-center overflow-hidden rounded-xl h-10 px-4 bg-red-500 text-white text-sm font-bold leading-normal tracking-[0.015em] mt-4">
                <%= submit_tag 'Delete Selected Files', name: 'action_type', value: 'Delete Selected Files' %>
              </div>
            </div>
            <!-- Flash message for delete -->
            <div id="delete-warning" style="color: red; margin-top: 10px;"></div>

          <% end %>
          <script>
          document.getElementById('delete').addEventListener('click', function(event){
            const checkboxes = document.querySelectorAll('input[name="selected_files[]"]:checked');

            const selectedFiles = Array.from(checkboxes).map(checkbox => checkbox.value);

            if(selectedFiles.length === 0){
              event.preventDefault();
              document.getElementById('delete-warning').innerHTML = 'No files selected for deletion!';
            } else {
              document.getElementById('delete-warning').innerHTML = '';
            }
          }); 
          </script>
          <script>
            document.getElementById('display-selected').addEventListener('click', function() {

              const checkboxes = document.querySelectorAll('input[name="selected_files[]"]:checked');

              const selectedFiles = Array.from(checkboxes).map(checkbox => checkbox.value);

              /* Can be deleted later */
              const selectedFilesDiv = document.getElementById('selected-files');
              selectedFilesDiv.innerHTML = selectedFiles.length > 0 ? 'Selected Files: ' + selectedFiles.join(', ') : 'No files selected.';
            });  
          </script>
        <% end %>
    
        <%= form_for :download, method: :get, url: download_path, id: 'download-form' do %>
          <%= submit_tag 'Download', style: 'display:none;' %>
        <% end %>
        <div class="flex justify-center">
              <div class="framed-button field flex min-w-[84px] max-w-[240px] cursor-pointer items-center justify-center overflow-hidden rounded-xl bg-blue-500 h-10 px-4 text-sm font-bold leading-normal tracking-[0.015em]">
                  <button id="download-selected">
                      <span class="truncate">Download Selected Files</span>
                  </button>
              </div>
            </div>

        <script>
          document.getElementById('download-selected').addEventListener('click', function() {
            const checkboxes = document.querySelectorAll('input[name="selected_files[]"]:checked');
            const selectedFiles = Array.from(checkboxes).map(checkbox => checkbox.value);
          
            const downloadForm = document.getElementById('download-form');
          
            // Clear existing form data to make sure download does not error out due to duplicate filenames
            // Otherwise, you may end up trying to download the same file twice
            while (downloadForm.hasChildNodes()) {
              downloadForm.removeChild(downloadForm.firstChild);
            }
            // Reset does not work here since the form is variable length and thus no default
          
            // Add selected files to the form
            for (let i = 0; i < selectedFiles.length; i++) {
              let curFileInput = document.createElement('input');
              curFileInput.type = 'hidden';
              curFileInput.name = 'selected_files[]';
              curFileInput.value = selectedFiles[i];
              downloadForm.appendChild(curFileInput); // Append list of selected files
            };
          
            downloadForm.submit(); // Submit selected files to download
          });          
        </script>

        <% if flash[:alert] %>
          <p style="color: red;"><%= flash[:alert] %></p>
        <% end %>
        <% if flash[:notice] %>
          <p style="color: green;"><%= flash[:notice] %></p>
        <% end %>


        <p class="text-[#111418] text-lg font-bold leading-tight tracking-[-0.015em] max-w-[480px] text-center">Upload your spreadsheet</p>

        <%= form_with url: uploads_path, local: true, multipart: true, method: :post do |form| %>
          <div class="field flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-xl h-10 px-4 bg-[#f0f2f4] text-[#111418] text-sm font-bold leading-normal tracking-[0.015em]">
            <%= form.file_field :csv_file, name: 'upload[csv_file]', accept: '.xlsx' %>
          </div>
          <div class="actions framed-button flex cursor-pointer items-center justify-center overflow-hidden rounded-xl h-10 px-4 text-sm font-bold leading-normal tracking-[0.015em] mt-4">
            <%= form.submit "Upload" %>
          </div>

        <% end %>
        
      </div>
    </div>
  </div>
</div>