config/routes.rb
Rails.application.routes.draw do
  # get "calendar/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root to: redirect("login/index")
  get "login/index", to: "login#index", as: "login"
  post "/logout", to: "sessions#logout", as: "logout"
  get "/auth/google_oauth2/callback", to: "sessions#omniauth"
  get "sessions/logout"
  get "sessions/omniauth"

  resources :admins
  get "welcome/index", to: "welcome#index", as: "welcome"
  get "welcome/download", to: "download#download", as: "download"
  post "uploads", to: "uploads#handle_upload", as: "uploads"
  # resources :uploads, only: [ :new, :create ]

  resources :calendar, only: [ :index ] do
    get :export, on: :collection
    get :download_unassigned_rjs, on: :collection
  end

  get "calendar", to: "calendar#index"

  # Route for deleting CSV
  delete "welcome/delete_csv_files", to: "welcome#delete_csv_files", as: "delete_csv_files"
  post "welcome/handle_files", to: "welcome#handle_files", as: "handle_files"
end

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "KANM Show Scheduling" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="" />
    <link rel="stylesheet" as="style" onload="this.rel='stylesheet'" href="https://fonts.googleapis.com/css2?display=swap&amp;family=Newsreader%3Awght%40400%3B500%3B700%3B800&amp;family=Noto+Sans%3Awght%40400%3B500%3B700%3B900"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body class="admin-body">
    <div class="relative flex size-full min-h-screen flex-col bg-white group/design-root overflow-x-hidden" style='font-family: Newsreader, "Noto Sans", sans-serif;'>
      <div class="layout-container flex h-full grow flex-col">

        <header class="admin-nav-bar" style="background-color: rgba(80, 0, 0, 0.7);">
          <div class="admin-nav-bar-div-1 text-[#111418] flex-grow" style="margin-top: -1px; ">
            <div class="size-4" style="width: auto; margin-top: -4px;">
              <img src="<%= asset_path('KANMLogo.webp') %>" alt="KANM Logo" style="width: 60px; height: auto;" />
            </div>

            <h2 class="text-[#111418] text-lg font-bold leading-tight tracking-[-0.015em]" style="font-size: 1.15rem;">Radio Show Scheduling</h2>
          </div>

          <div class="admin-nav-bar-div-2">
            <div class="flex gap-2">
              <div class="dropdown">
                <i class="fa fa-user-o" aria-hidden="true">
                  <div class="dropdown-content">
                    <%= button_to "Logout", logout_path, class: "admin-button"%>
                    <% if @current_logged_in_admin.super_user? %>
                        <%= link_to "Manage Admins", admins_path, class: "admin-button admin-button-link" %>
                    <% end %>
                  </div>
                </i>
              </div>
            </div>
          </div>
        </header>

        <main>
          <%= yield %>
        </main>
        
        <div class = "container" style="margin-bottom: 10px;">
            <%= link_to "Back to Welcome Page", welcome_path %>
        </div>

      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "KANM Show Scheduling" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="" />
    <link rel="stylesheet" as="style" onload="this.rel='stylesheet'" href="https://fonts.googleapis.com/css2?display=swap&amp;family=Newsreader%3Awght%40400%3B500%3B700%3B800&amp;family=Noto+Sans%3Awght%40400%3B500%3B700%3B900"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
    <!-- If certain CSS might not be getting inherited right, try checking it once by disabling tailwind-->
  </head>

  <body>
    <div class="relative flex size-full min-h-screen flex-col bg-white group/design-root overflow-x-hidden" style='font-family: Newsreader, "Noto Sans", sans-serif;'>
      <div class="layout-container flex h-full grow flex-col">

        <header class="flex items-center justify-between whitespace-nowrap border-b border-solid border-b-[#f0f2f4] px-10 py-3 w-full" style="background-color: rgba(80, 0, 0, 0.7);">
          <div class="flex items-center gap-4 text-[#111418] flex-grow" style="margin-top: -1px;">
            <div class="size-4" style="width: 60px; margin-top: -10px;"> <!-- Set a fixed width here -->
              <img src="<%= asset_path('KANMLogo.webp') %>" alt="KANM Logo" class="w-full h-auto" /> <!-- w-full for full width within container -->
            </div>
            <h2 class="text-[#111418] text-lg font-bold leading-tight tracking-[-0.015em]">Radio Show Scheduling</h2>
          </div>

          <div class="flex flex-1 justify-end gap-8">
            <div class="flex gap-2">
              <div class="dropdown">
                <i class="fa fa-user-o" aria-hidden="true">
                  <div class="dropdown-content">
                    <%= button_to "Logout", logout_path, class: "admin-button"%>
                    <% if @current_logged_in_admin.super_user? %>
                      <%= link_to "Manage Admins", admins_path, class: "admin-button" %>
                    <% end %>
                  </div>
                </i>
              </div>
            </div>
          </div>
        </header>

        <main>
          <%= yield %>
        </main>

      </div>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<html>
  <head>
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="" />
    <link
      rel="stylesheet"
      as="style"
      onload="this.rel='stylesheet'"
      href="https://fonts.googleapis.com/css2?display=swap&amp;family=Newsreader%3Awght%40400%3B500%3B700%3B800&amp;family=Noto+Sans%3Awght%40400%3B500%3B700%3B900"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
  </head>
  <body>
    <div class="relative flex size-full min-h-screen flex-col bg-white group/design-root overflow-x-hidden" style='font-family: Newsreader, "Noto Sans", sans-serif;'>
      <div class="layout-container flex h-full grow flex-col">
        <header class="flex items-center justify-between whitespace-nowrap border-b border-solid border-b-[#f0f2f4] px-10 py-3" style="background-color: rgba(80, 0, 0, 0.7);">
          <div class="flex items-center gap-4 text-[#111418]">
            <div class="size-4" style="width: 60px; background-color: ; margin-top: -10px;"> <!-- Set a fixed width here -->
              <img src="<%= asset_path('KANMLogo.webp') %>" alt="KANM Logo" class="w-full h-auto" /> <!-- w-full for full width within container -->
            </div>
            <h2 class="text-[#111418] text-lg font-bold leading-tight tracking-[-0.015em]">Radio Show Scheduling</h2>
          </div>
          <div class="flex gap-2">
            <%= button_to "/auth/google_oauth2", class: "flex max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-xl h-10 bg-[#f0f2f4] text-[#111418] gap-2 text-sm font-bold leading-normal tracking-[0.015em] min-w-0 px-2.5" do %>
                <img src="https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-1024.png" alt="Google Logo" style="height: 25px; width: 25px; margin-top: -2px;">
                <span>Login with TAMU Gmail</span>
            <% end %>
            </div>
        </header>
        
        <main>
            <%= yield %>
        </main>
        
      </div>
    </div>
  </body>
</html>